name: Bug Report
description: Report a bug or unexpected behavior
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Add directive to document...
        2. Build documentation...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant parts of your conf.py
      render: python
      placeholder: |
        extensions = [
            "sphinx_needs",
            "sphinx_needs_tree_map",
        ]
        needtreemap_colors = {...}

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide version information
      placeholder: |
        - Python version:
        - Sphinx version:
        - sphinx-needs version:
        - sphinx-needs-tree-map version:
        - Operating system:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any error messages or tracebacks
      render: shell
